
SET IDENTITY_INSERT [dbo].[Accounts] ON 
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (4, N'1010', N'Cash in Bank', N'Cash in Bank', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (5, N'1020', N'Petty Cash', N'Petty Cash', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (6, N'1100', N'Accounts Receivable', N'Accounts Receivable', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (7, N'1200', N'Inventory', N'Inventory', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (8, N'1300
', N'Prepaid Expenses', N'Prepaid Expenses', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (9, N'1400', N'Fixed Assets (Furniture, Equipment)', N'Fixed Assets (Furniture, Equipment)', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (10, N'1500
', N'Accumulated Depreciation', N'Accumulated Depreciation', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (11, N'2010', N'Accounts Payable', N'Accounts Payable', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (12, N'2100
', N'Loans Payable', N'Loans Payable', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (13, N'2200
', N'Taxes Payable', N'Taxes Payable', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (14, N'2300', N'Salaries Payable', N'Salaries Payable', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (15, N'4100', N'Sales Revenue', N'Sales Revenue', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (16, N'4200', N'Discounts Given', N'Discounts Given', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (17, N'4300', N'Other Income', N'Other Income', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (18, N'5100', N'Cost of Goods Sold', N'Cost of Goods Sold', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (19, N'5200', N'Rent Expense', N'Rent Expense', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (20, N'5300', N'Utilities Expense', N'Utilities Expense', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (21, N'5400', N'Salaries & Wages Expense', N'Salaries & Wages Expense', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (22, N'5500', N'Advertising Expense', N'Advertising Expense', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
INSERT [dbo].[Accounts] ([AccountID], [AccountCode], [AccountName], [Description], [CreatedBy], [DateCreated]) VALUES (24, N'5600', N'Office Supplies', N'Office Supplies', N'admin', CAST(N'2025-05-22T00:00:00.0000000' AS DateTime2))
GO
SET IDENTITY_INSERT [dbo].[Accounts] OFF
GO





